name: Build boot 5PRO

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "请输入要获取的 release 版本 tag（如 PKR110_15.0.0.840(CN01)，留空则自动获取最新）"
        required: false
      file_name:
        description: "请选择要获取的文件"
        required: true
        default: boot.img
        type: choice
        options:
          - boot.img
          - init_boot.img
          - fastboot_firmware.zip

  push:
    tags:
      - "v*.*.*"

env:
  TZ: Asia/Shanghai
  CCACHE_DIR: ${{ github.workspace }}/ccache
  CCACHE_COMPRESS: 1
  CCACHE_MAXSIZE: 10G

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-latest
    env:
      CLANG_VERSION: Clang-19.0.0git-20240723
    permissions:
      contents: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Set swap to 10G
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Get asset download url from tag and file name
        id: get-asset-url
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          file="${{ github.event.inputs.file_name }}"

          if [ -n "${{ github.event.inputs.tag_name }}" ]; then
            tag="${{ github.event.inputs.tag_name }}"
            api="https://api.github.com/repos/rin0011/opace5_pro_fw/releases/tags/$tag"
            asset_url=$(curl -s "$api" | jq -r --arg file "$file" '.assets[] | select(.name==$file) | .browser_download_url')
            if [ -z "$asset_url" ] || [ "$asset_url" == "null" ]; then
              echo "::error::未找到 $file (tag: $tag)"
              exit 1
            fi
          else
            # 自动获取最新 release
            api="https://api.github.com/repos/rin0011/opace5_pro_fw/releases/latest"
            asset_url=$(curl -s "$api" | jq -r --arg file "$file" '.assets[] | select(.name==$file) | .browser_download_url')
            if [ -z "$asset_url" ] || [ "$asset_url" == "null" ]; then
              echo "::error::未找到最新发行版中的 $file"
              exit 1
            fi
          fi
          echo "ASSET_URL=$asset_url" >> $GITHUB_ENV

      - name: Download selected asset
        run: |
          file="${{ github.event.inputs.file_name }}"
          curl -fL "$ASSET_URL" -o "$file"
          if [ ! -f "$file" ]; then
            echo "::error::文件下载失败"
            exit 1
          fi
          filesize=$(wc -c < "$file")
          echo "$file 文件大小: $filesize 字节"
          if [ "$filesize" -lt 10240 ]; then
            echo "::warning::$file 文件大小异常 ($filesize 字节) - 可能是无效文件"
          fi
          echo "BOOT_IMG_PATH=$GITHUB_WORKSPACE/$file" >> $GITHUB_ENV

      - name: Setup build kernel environment
        run: |
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%y%m%d")" >> $GITHUB_ENV
          sudo apt-get update
          sudo apt-get install -y git dwarves libelf-dev ccache automake flex bison build-essential \
            zlib1g-dev libncurses5-dev libc6-dev-i386 bc device-tree-compiler python3 make pahole \
            libssl-dev libffi-dev libxml2-dev libxslt1-dev libgmp-dev libmpfr-dev libmpc-dev unzip
          mkdir -p $GITHUB_WORKSPACE/kernel_workspace
          mkdir -p "${CCACHE_DIR}"
          ccache --set-config=cache_dir="${CCACHE_DIR}"
          ccache --set-config=max_size="${CCACHE_MAXSIZE}"
          ccache --set-config=compression=true
          ccache --set-config=compression_level=6
          ccache --set-config=hash_dir=false
          ccache --set-config=sloppiness=file_macro,locale,time_macros
          ccache --show-config
          ccache -z


      - name: Setup build date
        id: date
        run: |
          current_date=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
          echo "current-date=${current_date}" >> $GITHUB_OUTPUT


      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ env.CLANG_VERSION }}-${{ hashFiles('**/Kbuild') }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ env.CLANG_VERSION }}-
            ccache-${{ runner.os }}-

      - name: Cache Clang toolchain
        id: cache-clang
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/kernel_workspace/clang-aosp
          key: ${{ env.CLANG_VERSION }}

      - name: Download & extract Clang-aosp using aria2
        if: ${{ steps.cache-clang.outputs.cache-hit != 'true' }}
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          mkdir -p clang-aosp
          wget -O zyclang.tar.gz https://github.com/ZyCromerZ/Clang/releases/download/19.0.0git-20240723-release/Clang-19.0.0git-20240723.tar.gz
          tar -C clang-aosp -zxvf zyclang.tar.gz



      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: brokestar233/android_kernel_common_oneplus_sm8750
          ref: v8
          path: kernel_workspace/android-kernel
          
      - name: Checkout susfs4ksu
        uses: actions/checkout@v4
        with:
          repository: ShirkNeko/susfs4ksu
          ref: gki-android15-6.6
          path: kernel_workspace/susfs4ksu
          
      - name: Checkout SukiSU_patch
        uses: actions/checkout@v4
        with:
          repository: ShirkNeko/SukiSU_patch
          path: kernel_workspace/SukiSU_patch

      - name: Checkout sched_ext
        uses: actions/checkout@v4
        with:
          repository: HanKuCha/sched_ext
          path: kernel_workspace/sched_ext

      - name: Copy sched_ext
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          cp -r ./sched_ext/* ./android-kernel/kernel/sched

      - name: Patch setlocalversion
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/scripts
          sed -i 's/ -dirty//g' setlocalversion
          sed -i 's/OKI/android15-8/g' setlocalversion


      - name: Setup KernelSU
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
          KSU_VERSION=$(cd KernelSU && expr $(/usr/bin/git rev-list --count main) + 10700)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

      - name: Setup susfs
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          cp -r ../susfs4ksu/kernel_patches/fs/* ./fs/
          cp -r ../susfs4ksu/kernel_patches/include/linux/* ./include/linux/
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch ./
          cp ../SukiSU_patch/hooks/syscall_hooks.patch ./
          patch -p1 < 50_add_susfs_in_gki-android15-6.6.patch || true
          patch -p1 -F 3 < syscall_hooks.patch || true

      - name: Apply HMBird GKI patch
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/drivers
          cat << 'EOF' > hmbird_patch.c
          #include <linux/init.h>
          #include <linux/module.h>
          #include <linux/of.h>
          #include <linux/slab.h>
          #include <linux/string.h>
          #include <linux/printk.h>
          #include <linux/errno.h>
          static int __init hmbird_patch_init(void)
          {
              struct device_node *ver_np;
              const char *type;
              int ret;
              ver_np = of_find_node_by_path("/soc/oplus,hmbird/version_type");
              if (!ver_np) {
                   pr_info("hmbird_patch: version_type node not found\n");
                   return 0;
              }
              ret = of_property_read_string(ver_np, "type", &type);
              if (ret) {
                   pr_info("hmbird_patch: type property not found\n");
                   of_node_put(ver_np);
                   return 0;
              }
              if (strcmp(type, "HMBIRD_OGKI") != 0) {
                   of_node_put(ver_np);
                   return 0;
              }
              struct property *prop = of_find_property(ver_np, "type", NULL);
              if (prop) {
                   struct property *new_prop = kmalloc(sizeof(*prop), GFP_KERNEL);
                   if (!new_prop) {
                        pr_err("hmbird_patch: kmalloc for new_prop failed\n");
                        of_node_put(ver_np);
                        return -ENOMEM;
                   }
                   memcpy(new_prop, prop, sizeof(*prop));
                   new_prop->value = kstrdup("HMBIRD_GKI", GFP_KERNEL);
                   if (!new_prop->value) {
                        pr_err("hmbird_patch: kmalloc for new_prop->value failed\n");
                        kfree(new_prop);
                        of_node_put(ver_np);
                        return -ENOMEM;
                   }
                   new_prop->length = strlen("HMBIRD_GKI") + 1;
                   if (of_remove_property(ver_np, prop)) {
                        pr_err("hmbird_patch: of_remove_property failed\n");
                        kfree(new_prop->value);
                        kfree(new_prop);
                        of_node_put(ver_np);
                        return -EINVAL;
                   }
                   if (of_add_property(ver_np, new_prop)) {
                        pr_err("hmbird_patch: of_add_property failed\n");
                        kfree(new_prop->value);
                        kfree(new_prop);
                        of_node_put(ver_np);
                        return -EINVAL;
                   }
                   pr_info("hmbird_patch: success from HMBIRD_OGKI to HMBIRD_GKI\n");
              }
              else {
                  pr_info("hmbird_patch: type property structure not found\n");
              }
              of_node_put(ver_np);
              return 0;
          }
          early_initcall(hmbird_patch_init);
          MODULE_LICENSE("GPL");
          MODULE_AUTHOR("reigadegr");
          MODULE_DESCRIPTION("Forcefully convert HMBIRD_OGKI to HMBIRD_GKI.");
          EOF
          if ! grep -q "hmbird_patch.o" Makefile; then
              echo "obj-y += hmbird_patch.o" >> Makefile
          fi

      - name: Add SUSFS Configuration Settings
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          sed -i 's/check_defconfig//' ./build.config.gki
          if [ ! -f "arch/arm64/configs/gki_defconfig" ]; then
              echo "错误: gki_defconfig 文件不存在！"
              ls -la arch/arm64/configs
              exit 1
          fi


          cat <<EOF >> arch/arm64/configs/gki_defconfig
          CONFIG_KSU=y
          CONFIG_KSU_SUSFS_SUS_SU=n
          CONFIG_KSU_MANUAL_HOOK=y
          CONFIG_KSU_SUSFS=y
          CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_PATH=y
          CONFIG_KSU_SUSFS_SUS_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_KSTAT=y
          CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n
          CONFIG_KSU_SUSFS_TRY_UMOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_SPOOF_UNAME=y
          CONFIG_KSU_SUSFS_ENABLE_LOG=y
          CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
          CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
          CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
          CONFIG_AUTOFDO_CLANG=y
          CONFIG_LD_DEAD_CODE_DATA_ELIMINATION=y
          CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y
          EOF
          echo "CONFIG_LOCALVERSION=\"-g013ec21bba94-abogki383916444-4k\"" >> arch/arm64/configs/gki_defconfig

      # 18. Kernel 编译
      - name: Build kernel
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel

          export KBUILD_BUILD_TIMESTAMP='Tue Dec 17 23:36:49 UTC 2024'
          export CCACHE_BASEDIR="$GITHUB_WORKSPACE"
          export CC="ccache clang"
          export CXX="ccache clang++"
          export ARCH=arm64
          export SUBARCH=arm64
          export HEADER_ARCH=arm64
          export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$PATH
          export KBUILD_BUILD_HOST=localhost
          export KBUILD_BUILD_USER=Builder
          export LLVM=1
          export LLVM_IAS=1
          export KCFLAGS="-O2 -Wno-error"
          export KMI="SYSTEM_DLKM_RE_SIGN=0 BUILD_SYSTEM_DLKM=0 KMI_SYMBOL_LIST_STRICT_MODE=0"

          echo "===== 验证工具链 ====="
          which clang || { echo "错误: Clang 未找到！"; exit 1; }
          clang --version
          which ld.lld || { echo "错误: ld.lld 未找到！"; exit 1; }
          ld.lld --version

          make O=out ARCH=$ARCH SUBARCH=$SUBARCH gki_defconfig

          echo "===== 开始构建内核 ====="
          make -s O=out -j$(nproc --all) \
              ARCH=$ARCH \
              SUBARCH=$SUBARCH \
              HEADER_ARCH=$HEADER_ARCH \
              CC="$CC" \
              CXX="$CXX" \
              LD=ld.lld \
              AR=llvm-ar \
              NM=llvm-nm \
              OBJCOPY=llvm-objcopy \
              OBJDUMP=llvm-objdump \
              READELF=llvm-readelf \
              OBJSIZE=llvm-size \
              STRIP=llvm-strip \
              KCFLAGS="$KCFLAGS" \
              KMI="$KMI" \
              CLANG_AUTOFDO_PROFILE="../android/gki/aarch64/afdo/kernel.afdo"

          # 显示ccache统计
          ccache -s

      - name: Check kernel output files
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          if [ -f android-kernel/out/arch/arm64/boot/Image ]; then
            echo "CHECK_IMAGE=true" >> $GITHUB_ENV
          else
            echo "Kernel output file is empty"
            ls -la android-kernel/out/arch/arm64/boot
            tail -n 100 android-kernel/out/build.log || true
            exit 1
          fi

      - name: Make Anykernel3
        if: ${{ env.CHECK_IMAGE == 'true' }}
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
          rm -rf AnyKernel3/.git
          cp android-kernel/out/arch/arm64/boot/Image AnyKernel3/

      # 获取 Magisk 最新版本和下载链接
      - name: Get Magisk latest version info
        id: magisk_version
        run: |
          MAGISK_JSON=$(curl -s https://api.github.com/repos/topjohnwu/Magisk/releases/latest)
          MAGISK_VERSION=$(echo "$MAGISK_JSON" | jq -r .tag_name)
          MAGISK_URL=$(echo "$MAGISK_JSON" | jq -r '.assets[] | select(.name | test("\\.apk$")) | .browser_download_url')
          echo "MAGISK_VERSION=$MAGISK_VERSION" >> $GITHUB_ENV
          echo "MAGISK_URL=$MAGISK_URL" >> $GITHUB_ENV

      # 基于版本号缓存 Magisk APK
      - name: Cache Magisk APK
        id: cache-magisk-apk
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/Magisk.apk
          key: magisk-apk-${{ env.MAGISK_VERSION }}

      # 未命中缓存时自动下载最新 Magisk APK
      - name: Download Magisk APK
        if: steps.cache-magisk-apk.outputs.cache-hit != 'true'
        run: |
          wget -O Magisk.apk "$MAGISK_URL"

      # 解包 magiskboot 可执行文件
      - name: Extract magiskboot from Magisk APK
        run: |
          unzip -o Magisk.apk 'lib/x86_64/libmagiskboot.so' -d magisk_extract
          mv magisk_extract/lib/x86_64/libmagiskboot.so magiskboot
          chmod +x magiskboot
          rm -rf magisk_extract
          echo "MAGISKBOOT_PATH=${GITHUB_WORKSPACE}/magiskboot" >> $GITHUB_ENV

      - name: Repack kernel to boot image
        if: ${{ env.CHECK_IMAGE == 'true' }}
        run: |
          cd "$GITHUB_WORKSPACE"
          if [ ! -f "$MAGISKBOOT_PATH" ]; then
            echo "::error::magiskboot tool not found at $MAGISKBOOT_PATH"
            exit 1
          fi
          if [ ! -f "$BOOT_IMG_PATH" ]; then
            echo "::error::Original boot.img not found at $BOOT_IMG_PATH"
            exit 1
          fi
          mkdir -p repack_workdir
          cd repack_workdir
          cp "$BOOT_IMG_PATH" ./boot.img
          "$MAGISKBOOT_PATH" unpack ./boot.img
          if [ ! -f "kernel" ]; then
            echo "::error::Failed to unpack boot.img"
            ls -la
            exit 1
          fi
          rm -f kernel
          cp "../kernel_workspace/android-kernel/out/arch/arm64/boot/Image" kernel
          "$MAGISKBOOT_PATH" repack ./boot.img
          if [ ! -f "new-boot.img" ]; then
            echo "::error::Failed to repack boot.img"
            exit 1
          fi
          mv new-boot.img "../boot-${KSUVER}.img"
          cd ..
          echo "REPACKED_BOOT_IMG_PATH=$GITHUB_WORKSPACE/boot-${KSUVER}.img" >> $GITHUB_ENV

      - name: Create Anykernel3 ZIP
        if: ${{ env.CHECK_IMAGE == 'true' }}
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/AnyKernel3
          zip -r9 "AnyKernel3-${KSUVER}.zip" . -x .gitignore
          mv "AnyKernel3-${KSUVER}.zip" $GITHUB_WORKSPACE/
          echo "ANY_KERNEL_ZIP_PATH=$GITHUB_WORKSPACE/AnyKernel3-${KSUVER}.zip" >> $GITHUB_ENV

      - name: Upload artifacts
        if: ${{ env.CHECK_IMAGE == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Artifacts-${{ env.KSUVER }}
          path: |
            kernel_workspace/android-kernel/out/arch/arm64/boot/Image
            ${{ env.ANY_KERNEL_ZIP_PATH }}
            ${{ env.REPACKED_BOOT_IMG_PATH }}
          retention-days: 7